export type Review = {
  REVIEW_ID: number;
  CUSTOMER_NAME: string;
  NATIONALITY: string;
  NUMBER_OF_FLIGHTS: number;
  DATE_SUBMITTED_ID: string;
  REVIEW_DAY_OF_WEEK_NAME: string;
  REVIEW_CAL_MONTH: number;
  REVIEW_CAL_MON_NAME: string;
  REVIEW_CAL_YEAR: number;
  DATE_FLOWN_ID: string;
  ORIGIN_LOCATION_ID: number;
  ORIGIN_CITY: string;
  ORIGIN_AIRPORT: string;
  DESTINATION_LOCATION_ID: number;
  DESTINATION_CITY: string;
  DESTINATION_AIRPORT: string;
  TRANSIT_LOCATION_ID: number;
  TRANSIT_CITY: string;
  TRANSIT_AIRPORT: string;
  AIRCRAFT_ID: number;
  AIRCRAFT_MODEL: string;
  AIRCRAFT_MANUFACTURER: string;
  SEAT_CAPACITY: number | null;
  VERIFIED: boolean;
  SEAT_TYPE: string;
  TYPE_OF_TRAVELLER: string;
  SEAT_COMFORT: number | null;
  CABIN_STAFF_SERVICE: number | null;
  FOOD_AND_BEVERAGES: number | null;
  INFLIGHT_ENTERTAINMENT: number | null;
  GROUND_SERVICE: number | null;
  WIFI_AND_CONNECTIVITY: number | null;
  VALUE_FOR_MONEY: number | null;
  AVERAGE_RATING: number | null;
  RATING_BAND: string | null;
  RECOMMENDED: boolean | null;
  REVIEW_TEXT: string;
  EL_UPDATED_AT: string;
  T_UPDATED_AT: string;
};
